### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by LukePrior** [rtcq/syncedlyrics#1]
![image](https://user-images.githubusercontent.com/22492406/205430378-4565724e-de0d-40df-b6ab-18b2e2a474b8.png)

I encountered this error when trying to use the library.

```
import syncedlyrics
lrc = syncedlyrics.search("Dua Lipa - Levitating", providers=["Deezer"])
```

**Comment by rtcq** [comment]
Thanks for the contribution, It should be solved now. Can you please upgrade the package via `pip install syncedlyrics -U`, and check again?

**Comment by rtcq** [comment]
No response, closing
