### ISSUE TITLE
Suggestion: lrclib.net

### ISSUE THREAD

**Issue by Vuizur** [rtcq/syncedlyrics#11]
It's a really cool straightforward API, written by the creator of lrcget: https://github.com/tranxuanthang/lrcget/issues/2

(I also noticed that Lyricsify is broken for me because they added the cloudflare bot protection. I fiddled a bit with it, but bypassing this is hard and might not be worth the effort.)

Thanks for creating this super useful library!

**Comment by rtcq** [comment]
Thank you for your suggestion, I appreciate it. Although I am not sure if this is another wrapper around Musixmatch or not ([was said to be](https://www.reddit.com/r/musichoarder/comments/yuwwt9/lrcget_opensource_utility_for_massdownloading_lrc/iwbmski/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)) but I think it is worth implementing it for sure.

**Comment by Vuizur** [comment]
Thanks a lot!
