### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by xizeyoupan** [rtcq/syncedlyrics#13]
I forked this repo and added asyncio support. And  I added the duration parameter if the provider supports it.
I also added a new Tencent provider.

https://github.com/xizeyoupan/syncedlyrics_aio

**Comment by rtcq** [comment]
Thanks for the contribution, I appreciate it.
Feel free to make PR so I can make some modifications if needed.

The problem with the async support is some packages like `spotdl` rely on the current not-async version and I think it would be incompatibility, therefore I think it is good to have it in another repo/package like yours.
Another solution is using `asyncio.run` to wrap all the async functions into a sync version of them, like https://stackoverflow.com/a/55365529/12696223

**Comment by xizeyoupan** [comment]
Yes , this is an alternative. I wish it would help if someone else needs async support.😛

**Comment by plutonium-239** [comment]
thank you for your work, both @xizeyoupan and @0x7d4 
the asyncio version is also great for easily timing out a search using asyncio's waiting syntax

**Comment by plutonium-239** [comment]
thank you for your work, both @xizeyoupan and @0x7d4 
the asyncio version is also great for easily timing out a search using asyncio's waiting syntax
