### ISSUE TITLE
Add Musixmatch provider

### ISSUE THREAD

**Issue by Piripe** [rtcq/syncedlyrics#5]
[Musixmatch](https://www.musixmatch.com/explore) is the lyrics provider of Spotify, Apple Music and other platforms, I think it would be nice to implement it.

Note: The media player [Rise-Media-Player](https://github.com/Rise-Software/Rise-Media-Player) (that is open-source) uses Musixmatch to get synced lyrics, you can read the code of RiseMP to understand how the Musixmatch API works.

**Comment by rtcq** [comment]
Thanks for the suggestion, can you tell me in which directory and file it's implemented because I could not find it via searching
